# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Python checks
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Build package
      run: |
        poetry build
    - name: Mypy checks
      run: |
        poetry run mypy stock_summary/
    - name: Pylint checks
      run: |
        poetry run pylint stock_summary/
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: ./dist
  installation-test:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: packages
          path: ./dist
      - name: Python checks
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.version }}
      - name: Package installation
        run: |
          ls ./dist
          pip install poetry
          pip install dist/stock_summary*.whl
      - name: Sanity tests
        run: |
          stock_summary_tool --help
          stock_summary_tool import-data -e stock_summary/demo_datasets/entries -p stock_summary/demo_datasets/portfolio -y
          stock_summary_tool export-data -d output_files/
      - name: Unit tests
        run: |
          poetry install
          make tests

          





